# -*- coding: utf-8 -*-
"""Pytesseract_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7oLsF7Va980zDm79_GPiBLZnQb55G4G

# Installations
"""

!mamba install -y -c conda-forge tesseract=5.0.0
!apt-get update
!apt-get install -y tesseract-ocr
!pip install pytesseract pillow numpy opencv-python matplotlib pandas requests jiwer

"""### Imports"""

import os
import re
import platform
import urllib.request
import requests
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pytesseract

from PIL import Image
from jiwer import wer, cer



"""### Download models and Version Check"""

import os
import urllib.request

Tessdata_dir = "/usr/share/tesseract-ocr/4.00/tessdata"
os.makedirs(Tessdata_dir, exist_ok=True)

models = {
    "deu_frak": "https://github.com/tesseract-ocr/tessdata/raw/main/deu_frak.traineddata",
    "deu": "https://github.com/tesseract-ocr/tessdata/raw/main/deu.traineddata",
    "eng": "https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata",
}

for name, url in models.items():
    out = os.path.join(Tessdata_dir, f"{name}.traineddata")
    if not os.path.exists(out):
        print(f"Downloading {name}...")
        urllib.request.urlretrieve(url, out)
    else:
        print(f"Already exists: {name}")

print("Done.")

import os
import urllib.request

Tessdata_dir = "/usr/share/tesseract-ocr/4.00/tessdata"

os.makedirs(Tessdata_dir, exist_ok=True)

print("Tesseract version:")
print(pytesseract.get_tesseract_version())

print("\nAvailable languages:")
print(pytesseract.get_languages(config=f'--tessdata-dir {Tessdata_dir}'))

"""# Download Dataset
Download historical German images from book
"""

import os
import platform

pages = [8, 9, 12, 38, 53, 78, 94, 105, 114, 115,
         146, 210, 314, 316, 457, 468, 490, 619, 615, 753]

base = "https://nlp.fi.muni.cz/projekty/ahisto/book_by_id/494/"

os.makedirs("images", exist_ok=True)
os_type = platform.system()
print("OS:", os_type)

for p in pages:
    path = f"images/{p}.jpg"

    if not os.path.exists(path):
        if os_type == "Windows":
            !curl -k -L -o {path} {base}{p}.jpg
        else:
            !wget -O {path} {base}{p}.jpg
    else:
        print(f"Already exists: {path}")

"""# Draw Bounding Box

"""

"""
Oem(OCR Engine Mode):

0	Legacy Tesseract engine only
1	LSTM engine only
2	Legacy + LSTM
3	Default (let Tesseract decide)


psm(Page Segmentation Mode):

0	Orientation and Script Detection (OSD) only
1	Automatic page segmentation with OSD
2	Automatic page segmentation, no OCR, no OSD
3	Fully automatic page segmentation (default)
4	Assume a single column of text of variable sizes
5	Assume a single uniform block of vertically aligned text
6	Assume a single uniform block of text
7	Treat image as a single text line
8	Treat image as a single word
9	Treat image as a single word in a circle
10	Treat image as a single character
11	Sparse text. Find as much text as possible
12	Sparse text with OSD
13	Raw line mode (single line, bypasses some hacks)

"""

def draw_bounding_boxes(image_path, psm=4, min_conf=0):
    import cv2
    import pytesseract
    import matplotlib.pyplot as plt

    image = cv2.imread(image_path)

    data = pytesseract.image_to_data(
        image,
        lang="deu_frak+deu",
        config=f"--oem 1 --psm {psm}", # output oem 1(OCR Engine Mode 1: LSTM neural network OCR engine) psm(Page Segmentation Mode) 4
        output_type=pytesseract.Output.DICT
    )

    img_boxes = image.copy()

    for i in range(len(data["text"])):
        txt = data["text"][i].strip()

        try:
            conf = float(data["conf"][i])
        except:
            conf = -1

        if txt != "" and conf > min_conf:
            x = data["left"][i]
            y = data["top"][i]
            w = data["width"][i]
            h = data["height"][i]

            cv2.rectangle(
                img_boxes,
                (x, y),
                (x + w, y + h),
                (0, 255, 0),
                1
            )

    plt.figure(figsize=(8, 12))
    plt.imshow(img_boxes)
    plt.title(f"Detected Text Boxes: {image_path}")
    plt.axis("off")
    plt.show()

    #return img_boxes

"""### Test image

"""

draw_bounding_boxes("images/146.jpg")

"""# Experiment 1 - Clean Baseline
Original image to OCR, Without preprocessing
"""

import os

output_dir = "outputs/Experiment_1"
os.makedirs(output_dir, exist_ok=True)

def extract_text_pytesseract(image_path, psm=4, oem=1):

    image = cv2.imread(image_path)

    text = pytesseract.image_to_string(
        image,
        lang="deu_frak+deu",
        config=f"--oem {oem} --psm {psm}"
    )

    return text

# test image
text = extract_text_pytesseract("images/8.jpg",psm=4,oem=1)

print(text)

for p in pages:
    print(f"\n==============================")
    print(f"Page {p}")
    print(f"==============================")

    image_path = f"images/{p}.jpg"
    output_path = os.path.join(output_dir, f"page_{p}.txt")

    #show bounding boxes
    draw_bounding_boxes(
        image_path,
        psm=4,
        min_conf=0
    )

    #extract text without preprocessing
    output_text = extract_text_pytesseract(
        image_path,
        psm=4,
        oem=1
    )

    print(output_text)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_text)

    print(f"Saved: {output_path}")

"""### Evaluation Experiment 1"""

def normalize_text(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    return text

results_exp1 = []

gold_base = "https://nlp.fi.muni.cz/projekty/ahisto/ocr-output/494/"

for p in pages:
    print(f"Evaluating page {p}...")

    gold_url = f"{gold_base}{p}.txt"
    gold_text = requests.get(gold_url).text

    pred_path = os.path.join(output_dir, f"page_{p}.txt")
    with open(pred_path, "r", encoding="utf-8") as f:
        pred_text = f.read()

    gold_norm = normalize_text(gold_text)
    pred_norm = normalize_text(pred_text)

    #compute metrics
    wer_score = wer(gold_norm, pred_norm)
    cer_score = cer(gold_norm, pred_norm)

    results_exp1.append({
        "page": p,
        "WER": wer_score,
        "CER": cer_score
    })

print("=== Experiment 1 Results: Pytesseract ===")
df_exp1 = pd.DataFrame(results_exp1)
df_exp1

mean_wer = df_exp1["WER"].mean()
mean_cer = df_exp1["CER"].mean()

print("=== Experiment 1 Results ===")
print(f"Mean WER: {mean_wer:.4f}")
print(f"Mean CER: {mean_cer:.4f}")

"""### Save the result"""

import os

output_dir_result_1 = "outputs/Results"
os.makedirs(output_dir_result_1, exist_ok=True)

import os
import matplotlib.pyplot as plt

mean_wer = df_exp1["WER"].mean()
mean_cer = df_exp1["CER"].mean()

save_path = os.path.join(output_dir_result_1, "experiment_1_results.png")

fig, ax = plt.subplots(figsize=(10, len(df_exp1) * 0.45 + 2))
ax.axis("off")


fig.suptitle("Experiment 1 Results - Pytesseract", fontsize=16, y=0.98)

summary_text = f"Mean WER: {mean_wer}    |    Mean CER: {mean_cer}"
fig.text(0.5, 0.90, summary_text, ha="center", va="center", fontsize=12)

# Table
table = ax.table(
    cellText=df_exp1.values,
    colLabels=df_exp1.columns,
    cellLoc="center",
    colLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.3)

ax.set_position([0.1, 0.08, 0.8, 0.78])

fig.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
plt.show()
plt.close(fig)

print("Saved:", save_path)

plt.figure(figsize=(12,6))

plt.plot(
    df_exp1["page"],
    df_exp1["WER"],
    marker="o",
    label="WER"
)

plt.plot(
    df_exp1["page"],
    df_exp1["CER"],
    marker="s",
    label="CER"
)

plt.xlabel("Page")
plt.ylabel("Error Rate")
plt.title("Experiment 1: OCR Error by Page")

plt.legend()
plt.grid(True)

plt.show()

"""# Experiment 2 - Noise
Salt and Pepper, Nosify, Distortion - Without Preprocessing
"""

import os

output_dir_2 = "outputs/Experiment_2"
os.makedirs(output_dir_2, exist_ok=True)

"""### Salt and Pepper Function

Salt-and-pepper method is inspired by (https://www.geeksforgeeks.org/python/add-a-salt-and-pepper-noise-to-an-image-with-python/)
"""

import numpy as np
from PIL import Image


# amount = how many pixels change
# amount = 0.2 -- 20% pixel changed, amount = 0.8 -- 80% pixel changed
# salt_vs_pepper = how many are white
# salt_vs_pepper = 0.2 -- 20% white, salt_vs_pepper = 0.8 -- 80% white


def add_salt_pepper(image, amount=0.005, salt_vs_pepper=0.5):

    img = np.array(image).copy()
    h, w = img.shape[:2]

    num_pixels = int(amount * h * w)
    num_salt = int(num_pixels * salt_vs_pepper)
    num_pepper = num_pixels - num_salt

    #salt -white
    ys = np.random.randint(0, h, num_salt)
    xs = np.random.randint(0, w, num_salt)
    img[ys, xs] = 255

    #pepper -black
    ys = np.random.randint(0, h, num_pepper)
    xs = np.random.randint(0, w, num_pepper)
    img[ys, xs] = 0

    return Image.fromarray(img)

"""### Image_Distortion
The image distortion methods are inspired from the Image_Distortion repository(https://github.com/namks/Image_Distortion/tree/main), specifically the zoom and resolution degradation methods.
"""

from PIL import Image

def zoom_img(image, zoom_scale=1.15):
    w, h = image.size
    x = w / 2
    y = h / 2

    cropped = image.crop((
        x - w / (2 * zoom_scale),
        y - h / (2 * zoom_scale),
        x + w / (2 * zoom_scale),
        y + h / (2 * zoom_scale)
    ))

    return cropped.resize((w, h), Image.BICUBIC)

def lower_res_img(image, scale=0.7):
    w, h = image.size
    low_res = image.resize((int(w * scale), int(h * scale)), Image.BICUBIC)
    return low_res.resize((w, h), Image.BICUBIC)

def add_image_distortion(image, zoom_scale=1.15, resolution_scale=0.7):
    image = zoom_img(image, zoom_scale=zoom_scale)
    image = lower_res_img(image, scale=resolution_scale)
    return image

"""### Noisy
Additional blurring effects were applied to simulate realistic degradation, inspired by data augmentation techniques such as Noisify
(https://github.com/dstl/Noisify)
"""

import cv2
import numpy as np
from PIL import Image

def add_blur(image, kernel_size=3):
    img = np.array(image)
    blurred = cv2.GaussianBlur(img, (kernel_size, kernel_size), 0)
    return Image.fromarray(blurred)

"""### Testing one image with Noise

#### Test Salt and Pepper
"""

from PIL import Image
import matplotlib.pyplot as plt

noise_image_test = "images/8.jpg"

img = Image.open(noise_image_test).convert("RGB")

plt.figure(figsize=(10,12))
plt.imshow(img)
plt.title("Original", fontsize=16)
plt.axis("off")
plt.show()

noisy_img = add_salt_pepper(img, amount=0.04,salt_vs_pepper=0.3)
plt.figure(figsize=(10,12))
plt.imshow(noisy_img)
plt.title("Noisy", fontsize=16)
plt.axis("off")
plt.show()

"""#### Test Image Distortion and BLurr"""

from PIL import Image
import matplotlib.pyplot as plt

noise_image_test2 = "images/753.jpg"
img1 = Image.open(noise_image_test2).convert("RGB")

#fixed zoom_scale
distorted_img = add_image_distortion(
    img1,
    zoom_scale=0.9,
    resolution_scale=0.8
)


blurred_img = add_blur(img1, kernel_size=5)

#original
plt.figure(figsize=(10,14))
plt.imshow(img1)
plt.title("Original", fontsize=18)
plt.axis("off")
plt.show()

#distorted
plt.figure(figsize=(10,14))
plt.imshow(distorted_img)
plt.title("Distorted", fontsize=18)
plt.axis("off")
plt.show()

#blur
plt.figure(figsize=(10,14))
plt.imshow(blurred_img)
plt.title("Blurred", fontsize=18)
plt.axis("off")
plt.show()

"""### Combining Three Functions
- add salt_pepper
- add image_distortion
- add blurr
"""

def apply_all_corruptions(image,sp_amount=0.005,sp_ratio=0.5,zoom_scale=1.15,resolution_scale=0.7,
                          blur_kernel=3):
    image = add_salt_pepper(
        image,
        amount=sp_amount,
        salt_vs_pepper=sp_ratio
    )

    image = add_image_distortion(
        image,
        zoom_scale=zoom_scale,
        resolution_scale=resolution_scale
    )

    image = add_blur(
        image,
        kernel_size=blur_kernel
    )

    return image

noise_image_test = "images/468.jpg"

img = Image.open(noise_image_test).convert("RGB")
combined_img = apply_all_corruptions(
    img,
    sp_amount=0.03,
    sp_ratio=0.2,
    zoom_scale=0.9,
    resolution_scale = 0.85,
    blur_kernel=3
)
#original
plt.figure(figsize=(10,14), dpi=150)
plt.imshow(img)
plt.title("Original", fontsize=18)
plt.axis("off")
plt.show()

#combined
plt.figure(figsize=(10,14), dpi=150)
plt.imshow(combined_img)
plt.title("Salt + Distortion + Blur", fontsize=18)
plt.axis("off")
plt.show()

"""### Apply corruption for all images"""

import os
os.makedirs("corrupted_images", exist_ok=True)

from PIL import Image

for p in pages:
    img = Image.open(f"images/{p}.jpg").convert("RGB")

    combined_img = apply_all_corruptions(
        img,
        sp_amount=0.03,
        sp_ratio=0.2,
        zoom_scale=0.9,
        resolution_scale=0.85,
        blur_kernel=3
    )

    combined_img.save(f"corrupted_images/{p}.jpg")

print("Done saving all corrupted images.")

"""#### Run Pytesseract for Corrupted Images"""

for p in pages:
    print(f"\n==============================")
    print(f"Page {p}")
    print(f"==============================")

    image_path = f"corrupted_images/{p}.jpg"
    output_path = os.path.join(output_dir_2, f"page_{p}.txt")

    draw_bounding_boxes(
        image_path,
        psm=4,
        min_conf=0
    )

    output_text = extract_text_pytesseract(
        image_path,
        psm=4,
        oem=1
    )

    print(output_text)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_text)

    print(f"Saved: {output_path}")

"""### Evaluation - Experiment 2"""

def normalize_text(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    return text

results_exp2 = []

gold_base = "https://nlp.fi.muni.cz/projekty/ahisto/ocr-output/494/"

for p in pages:
    print(f"Evaluating Experiment 2 - page {p}...")

    gold_url = f"{gold_base}{p}.txt"
    gold_text = requests.get(gold_url).text

    pred_path = os.path.join(output_dir_2, f"page_{p}.txt")
    with open(pred_path, "r", encoding="utf-8") as f:
        pred_text = f.read()

    gold_norm = normalize_text(gold_text)
    pred_norm = normalize_text(pred_text)

    #compute metrics
    wer_score = wer(gold_norm, pred_norm)
    cer_score = cer(gold_norm, pred_norm)

    results_exp2.append({
        "page": p,
        "WER": wer_score,
        "CER": cer_score
    })

print("=== Experiment 2 Results - Pytesseract ===")
df_exp2 = pd.DataFrame(results_exp2)
df_exp2

mean_wer_exp2 = df_exp2["WER"].mean()
mean_cer_exp2 = df_exp2["CER"].mean()

print("=== Experiment 2 Results ===")
print(f"Mean WER: {mean_wer_exp2:.4f}")
print(f"Mean CER: {mean_cer_exp2:.4f}")

"""

```
# This is formatted as code
```

### Save Result"""

import os
import matplotlib.pyplot as plt

mean_wer = df_exp2["WER"].mean()
mean_cer = df_exp2["CER"].mean()

save_path = os.path.join(output_dir_result_1, "experiment_2_results.png")

fig, ax = plt.subplots(figsize=(10, len(df_exp2) * 0.45 + 2))
ax.axis("off")


fig.suptitle("Experiment 2 Results - Pytesseract", fontsize=16, y=0.98)

summary_text = f"Mean WER: {mean_wer}    |    Mean CER: {mean_cer}"
fig.text(0.5, 0.90, summary_text, ha="center", va="center", fontsize=12)


table = ax.table(
    cellText=df_exp2.values,
    colLabels=df_exp2.columns,
    cellLoc="center",
    colLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.3)

ax.set_position([0.1, 0.08, 0.8, 0.78])

fig.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
plt.show()
plt.close(fig)

print("Saved:", save_path)

"""# Experiment 3"""

import os

output_dir_3 = "outputs/Experiment_3"
os.makedirs(output_dir_3, exist_ok=True)

def preprocess_image_v1(image_path):

    image = cv2.imread(image_path)

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    kernel = np.array([
        [0, -1, 0],
        [-1, 5, -1],
        [0, -1, 0]
    ])

    sharpened = cv2.filter2D(
        gray,
        -1,
        kernel
    )

    _, binary = cv2.threshold(
        sharpened,
        180,
        255,
        cv2.THRESH_BINARY
    )

    return binary

"""### test preprocessing on one image"""

from PIL import Image
import matplotlib.pyplot as plt

test_image_path = "images/468.jpg"

original = cv2.cvtColor(
    original,
    cv2.COLOR_BGR2RGB
)
img = Image.open(test_image_path)
preprocessed_img = preprocess_image_v1(test_image_path)

plt.figure(figsize=(10,14), dpi=120)
plt.imshow(img)
plt.title("Original", fontsize=18)
plt.axis("off")
plt.show()

plt.figure(figsize=(10,14), dpi=120)
plt.imshow(preprocessed_img, cmap="gray")
plt.title("Preprocessed", fontsize=18)
plt.axis("off")
plt.show()



"""### Evaluation -Experiment 3"""

def normalize_text(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    return text

results_exp3 = []

gold_base = "https://nlp.fi.muni.cz/projekty/ahisto/ocr-output/494/"

for p in pages:
    print(f"Evaluating Experiment 3 - page {p}...")

    gold_url = f"{gold_base}{p}.txt"
    gold_text = requests.get(gold_url).text

    pred_path = os.path.join(output_dir_3, f"page_{p}.txt")
    with open(pred_path, "r", encoding="utf-8") as f:
        pred_text = f.read()

    gold_norm = normalize_text(gold_text)
    pred_norm = normalize_text(pred_text)

    wer_score = wer(gold_norm, pred_norm)
    cer_score = cer(gold_norm, pred_norm)

    results_exp3.append({
        "page": p,
        "WER": wer_score,
        "CER": cer_score
    })

print("=== Experiment 3 Results -GPT5.4 ===")
df_exp3 = pd.DataFrame(results_exp3)
df_exp3

mean_wer_exp3 = df_exp3["WER"].mean()
mean_cer_exp3 = df_exp3["CER"].mean()

print("=== Experiment 2 Results ===")
print(f"Mean WER: {mean_wer_exp3:.4f}")
print(f"Mean CER: {mean_cer_exp3:.4f}")

"""[link text](https://)### Saved Result"""

import os
import matplotlib.pyplot as plt

mean_wer = df_exp3["WER"].mean()
mean_cer = df_exp3["CER"].mean()

save_path = os.path.join(output_dir_result_1, "experiment_3_results.png")

fig, ax = plt.subplots(figsize=(10, len(df_exp3) * 0.45 + 2))
ax.axis("off")


fig.suptitle("Experiment 3 Results - GPT-5.4", fontsize=16, y=0.98)

summary_text = f"Mean WER: {mean_wer}    |    Mean CER: {mean_cer}"
fig.text(0.5, 0.90, summary_text, ha="center", va="center", fontsize=12)

# Table
table = ax.table(
    cellText=df_exp3.values,
    colLabels=df_exp3.columns,
    cellLoc="center",
    colLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.3)

ax.set_position([0.1, 0.08, 0.8, 0.78])

fig.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
plt.show()
plt.close(fig)

print("Saved:", save_path)

"""# Experiment 4"""

import os

output_dir_4 = "outputs/Experiment_4"
os.makedirs(output_dir_4, exist_ok=True)

import os

os.makedirs("corrupted_preprocessed_images", exist_ok=True)

import cv2
import numpy as np
from PIL import Image

def preprocess_image_v3(image):
    img = np.array(image.convert("RGB"))

    #grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    #sharpening
    kernel = np.array([
        [0, -0.4, 0],
        [-0.4, 2.5, -0.4],
        [0, -0.4, 0]
    ])
    sharpened = cv2.filter2D(gray, -1, kernel)

    #balanced threshold
    _, binary = cv2.threshold(
        sharpened,
        145,
        255,
        cv2.THRESH_BINARY
    )

    return Image.fromarray(binary)



"""### apply preprocessed image to noisy images"""

from PIL import Image

for p in pages:
    img = Image.open(f"corrupted_images/{p}.jpg").convert("RGB")

    preprocessed_img = preprocess_image_v3(img)

    preprocessed_img.save(f"corrupted_preprocessed_images/{p}.jpg")

print("Done saving corrupted + preprocessed images.")

"""### Test one image"""

from PIL import Image
import matplotlib.pyplot as plt

test_page = 490

noisy_img = Image.open(f"corrupted_images/{test_page}.jpg").convert("RGB")
preprocessed_img = Image.open(f"corrupted_preprocessed_images/{test_page}.jpg")

plt.figure(figsize=(10,14), dpi=150)
plt.imshow(noisy_img)
plt.title("Noisy Image", fontsize=18)
plt.axis("off")
plt.show()

plt.figure(figsize=(10,14), dpi=150)
plt.imshow(preprocessed_img, cmap="gray")
plt.title("Noisy + Preprocessed", fontsize=18)
plt.axis("off")
plt.show()





"""### Evaluation -Experiment 4

*   List item
*   List item


"""

def normalize_text(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    return text

results_exp4 = []

gold_base = "https://nlp.fi.muni.cz/projekty/ahisto/ocr-output/494/"

for p in pages:
    print(f"Evaluating Experiment 4 - page {p}...")


    gold_url = f"{gold_base}{p}.txt"
    gold_text = requests.get(gold_url).text

    pred_path = os.path.join(output_dir_4, f"page_{p}.txt")
    with open(pred_path, "r", encoding="utf-8") as f:
        pred_text = f.read()

    gold_norm = normalize_text(gold_text)
    pred_norm = normalize_text(pred_text)


    wer_score = wer(gold_norm, pred_norm)
    cer_score = cer(gold_norm, pred_norm)

    results_exp4.append({
        "page": p,
        "WER": wer_score,
        "CER": cer_score
    })

print("=== Experiment 4 Results - GPT5.4 ===")
df_exp4 = pd.DataFrame(results_exp4)
df_exp4

mean_wer_exp4 = df_exp4["WER"].mean()
mean_cer_exp4 = df_exp4["CER"].mean()

print("=== Experiment 4 Results ===")
print(f"Mean WER: {mean_wer_exp4:.4f}")
print(f"Mean CER: {mean_cer_exp4:.4f}")

"""#### Save result"""

import os
import matplotlib.pyplot as plt

mean_wer = df_exp4["WER"].mean()
mean_cer = df_exp4["CER"].mean()

save_path = os.path.join(output_dir_result_1, "experiment_4_results.png")

fig, ax = plt.subplots(figsize=(10, len(df_exp4) * 0.45 + 2))
ax.axis("off")


fig.suptitle("Experiment 4 Results - GPT-5.4", fontsize=16, y=0.98)

summary_text = f"Mean WER: {mean_wer}    |    Mean CER: {mean_cer}"
fig.text(0.5, 0.90, summary_text, ha="center", va="center", fontsize=12)


table = ax.table(
    cellText=df_exp4.values,
    colLabels=df_exp4.columns,
    cellLoc="center",
    colLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.3)

ax.set_position([0.1, 0.08, 0.8, 0.78])

fig.savefig(save_path, dpi=300, bbox_inches="tight", facecolor="white")
plt.show()
plt.close(fig)

print("Saved:", save_path)